
export const filters = [
    {
        id: "original" as const,
        name: "Original",
        cssFilter: "none",
        category: "basicos",
        mixBlendMode: undefined,
        background: undefined,
    },
    {
        id: "vintage" as const,
        name: "Vintage",
        cssFilter: "sepia(0.5) contrast(1.2) brightness(1.1)",
        category: "basicos",
        mixBlendMode: undefined,
        background: undefined,
    },
    {
        id: "pb" as const,
        name: "P&B",
        cssFilter: "grayscale(1) contrast(1.1)",
        category: "basicos",
        mixBlendMode: undefined,
        background: undefined,
    },
    {
        id: "frio" as const,
        name: "Frio",
        cssFilter: "brightness(1.1) saturate(1.2) hue-rotate(180deg)",
        category: "basicos",
        mixBlendMode: undefined,
        background: undefined,
    },
    {
        id: "quente" as const,
        name: "Quente",
        cssFilter: "brightness(1.1) saturate(1.3) sepia(0.3)",
        category: "basicos",
        mixBlendMode: undefined,
        background: undefined,
    },
    {
        id: "contraste" as const,
        name: "Contraste",
        cssFilter: "contrast(1.5) brightness(1.1)",
        category: "basicos",
        mixBlendMode: undefined,
        background: undefined,
    },
    {
        id: "fade" as const,
        name: "Fade",
        cssFilter: "contrast(0.9) brightness(1.2) saturate(0.8)",
        category: "basicos",
        mixBlendMode: undefined,
        background: undefined,
    },
    {
        id: "drama" as const,
        name: "Drama",
        cssFilter: "contrast(1.4) brightness(0.9) saturate(1.2)",
        category: "basicos",
        mixBlendMode: undefined,
        background: undefined,
    },
    {
        id: "sepia" as const,
        name: "Sépia",
        cssFilter: "sepia(1) brightness(1.1)",
        category: "basicos",
        mixBlendMode: undefined,
        background: undefined,
    },
    {
        id: "saturado" as const,
        name: "Saturado",
        cssFilter: "saturate(2) contrast(1.1)",
        category: "basicos",
        mixBlendMode: undefined,
        background: undefined,
    },
    {
        id: "invertido" as const,
        name: "Invertido",
        cssFilter: "invert(1) hue-rotate(180deg)",
        category: "basicos",
        mixBlendMode: undefined,
        background: undefined,
    },
    {
        id: "roxo" as const,
        name: "Roxo",
        cssFilter: "hue-rotate(270deg) saturate(1.5) brightness(0.9)",
        category: "duotone",
        mixBlendMode: undefined,
        background: undefined,
    },
    {
        id: "azul" as const,
        name: "Azul",
        cssFilter: "hue-rotate(200deg) saturate(1.3) brightness(1.1)",
        category: "duotone",
        mixBlendMode: undefined,
        background: undefined,
    },
    {
        id: "verde" as const,
        name: "Verde",
        cssFilter: "hue-rotate(90deg) saturate(1.4) brightness(1.1)",
        category: "duotone",
        mixBlendMode: undefined,
        background: undefined,
    },
    {
        id: "rosa" as const,
        name: "Rosa",
        cssFilter: "hue-rotate(320deg) saturate(1.5) brightness(1.2)",
        category: "duotone",
        mixBlendMode: undefined,
        background: undefined,
    },
    {
        id: "laranja" as const,
        name: "Laranja",
        cssFilter: "hue-rotate(30deg) saturate(1.6) brightness(1.1)",
        category: "duotone",
        mixBlendMode: undefined,
        background: undefined,
    },
    {
        id: "red" as const,
        name: "Red",
        cssFilter: "contrast(0.6) saturate(1.2) brightness(1.2)",
        category: "basicos",
        mixBlendMode: "hard-light",
        background: "#282581",
        imageMixBlendMode: "luminosity",
    },
    {
        id: "blue" as const,
        name: "Blue",
        cssFilter: "brightness(0.6)",
        category: "basicos",
        mixBlendMode: "hard-light",
        background: "#0066BF",
        imageMixBlendMode: "luminosity",
    },
    {
        id: "yellow" as const,
        name: "Yellow",
        cssFilter: "brightness(3.5)",
        category: "basicos",
        mixBlendMode: "soft-light",
        background: "#EF3CB4",
        imageMixBlendMode: "luminosity",
    },
    {
        id: "red-light" as const,
        name: "Red Light",
        cssFilter: "saturate(4) contrast(1.5)",
        category: "basicos",
        mixBlendMode: "color-dodge",
        background: "#282581",
        imageMixBlendMode: "lighten",
    },
    {
        id: "yellow-light" as const,
        name: "Yellow Light",
        cssFilter: "brightness(3) hue-rotate(93deg) contrast(2) saturate(1.5)",
        category: "duotone",
        mixBlendMode: "color",
        background: "#EF3CB4",
        imageMixBlendMode: "lighten",
    },
    {
        id: "purple-light" as const,
        name: "Purple Light",
        cssFilter: "saturate(5.2) brightness(1.05) contrast(3.5)",
        category: "basicos",
        mixBlendMode: "hue",
        background: "#A37FC7",
        imageMixBlendMode: "lighten",
    },
    {
        id: "green-light" as const,
        name: "Green Light",
        cssFilter: "saturate(1) brightness(0.8) contrast(1.6)",
        category: "basicos",
        mixBlendMode: "color-dodge",
        background: "#2D3181",
        imageMixBlendMode: "lighten",
    },
    {
        id: "pink-light" as const,
        name: "Pink Light",
        cssFilter: "contrast(1) saturate(2.5)",
        category: "basicos",
        mixBlendMode: "lighten",
        background: "#FF468D",
        imageMixBlendMode: "lighten",
    },
    {
        id: "red-blue-light" as const,
        name: "Red Blue Light",
        cssFilter: "saturate(3) brightness(1.2)",
        category: "basicos",
        mixBlendMode: "screen",
        background: "linear-gradient(to bottom right, #3993E2, #E2544B)",
        imageMixBlendMode: "lighten",
    },
    {
        id: "blue-yellow" as const,
        name: "Blue Yellow",
        cssFilter: "none",
        category: "duotone",
        mixBlendMode: "hue",
        background: "linear-gradient(to top left, #55ACEE, #FEDD31)",
        imageMixBlendMode: "luminosity",
    },
    {
        id: "pink-yellow" as const,
        name: "Pink Yellow",
        cssFilter: "none",
        category: "duotone",
        mixBlendMode: "hard-light",
        background: "linear-gradient(to bottom right, #FAA6FB, #FBBC05)",
        imageMixBlendMode: "luminosity",
    },
    {
        id: "red-blue" as const,
        name: "Red Blue",
        cssFilter: "none",
        category: "duotone",
        mixBlendMode: "hard-light",
        background: "linear-gradient(to bottom right, #3993E2, #E2544B)",
        imageMixBlendMode: "luminosity",
    },
];
